### ISSUE TITLE
Multiple Population with selection

### ISSUE THREAD

**Issue by stsmall** [kern-lab/discoal#15]
Hi @andrewkern,
Sorry for what is likely a lazy question. I would like to simulate 2 populations with discoal with 1 population under selection. Does discoal allow this? If not, what is the behavior with >1 populations and selection? Are both populations under selection? This command runs, I just want to verify that I understand it. I assume that both populations are under selection starting at time  designated by option Pu.
'discoal 12 1000 55000 -Pt 154 698 -Pr 344 1556 -ed 2 12 0 -ws 0 -Pa 450 4500 -Pu 0.000000 0.00045 -x 0.045454545454545456 -ed 1 0 1'
thanks,
@stsmall

**Comment by andrewkern** [comment]
hey @stsmall- `discoal` only simulates sweeps in a single population (popn 0) even if there are multiple populations in the simulation. this is mostly because the bookkeeping gets complex if sweeps are going through more than one population, and i'm yet to try to build it. 

i make a further simplifying assumption in the case of multi population models, where during the sweep phase (the short period of time in which the beneficial mutation is segregating) migration between popn 0 (i.e. the one with a sweep) and all other populations is set to zero. Migration can carry on as normal among the other populations however.

**Comment by stsmall** [comment]
Great! Thank you!
